### ISSUE TITLE
Do you need to setup the checkerboard grid size in the config ?

### ISSUE THREAD

**Issue by huangchaoxing** [hushunda/CameraLaserCalibrate#1]
Hi,

May I ask if we need to setup the  checkerboard grid size in the config ? If yes, then which item is correpond to the checkerboard grid size setting ?
Thank you

**Comment by hushunda** [comment]
yes.you need modify tag_size, checkerboard and  chose tag_type  in  Config.py 。

**Comment by huangchaoxing** [comment]
OK. Thank u.
